name: Build, test and Deploy Workflow
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  yarn-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.6'
      - name: Lint and check yarn.lock
        run: yarn run checks
      - name: Build
        run: yarn run build
